# Add 'service' label to any change to microservice files within the source dir
aslan:
- pkg/microservice/aslan/*

cron:
- pkg/microservice/cron/*

podexec:
- pkg/microservice/podexec/*

predator:
- pkg/microservice/predator/*

reaper:
- pkg/microservice/reaper/*

warpdrive:
- pkg/microservice/warpdrive/*

hubserver:
- pkg/microservice/hubserver/*